### PR TITLE
Fix/card responsiveness

### LINKED ISSUE #288: Home - fixing responsivesness for cards
# Description

The cards for the "Our Projects" and "Get Involved" need updates to their responsiveness.

* On medium screen sizes and above they should always be 3 in a row
* On small screen sizes they can be stacked on top of each other
* For contact us inceasing the right padding next to the buttons and flexbox on samller screens

Image

Image

On these page sizes the cards should shrink in width and be all on one horizontal row.

# Definiton of Done
- [ ] Adjust card responsiveness

### PR DESCRIPTION
**Pull request by aemerson1**
Issue: (#228) [https://github.com/stevensblueprint/blueprint_website/issues/288]

image

image

### CODE REVIEW

File: src/_components/GetInvolvedCard.jsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ export default function GetInvolvedCard({
   redirect_url,
 }) {
   return (
-    <figure className="flex flex-col w-full border border-black rounded-lg lg:p-5 p-8 lg:max-w-[445px] h-[450px]">
+    <figure className="flex flex-col border border-black rounded-lg lg:p-5 p-5 lg:h-[450px]">
```
Comment (Caposto) [inline src/_components/GetInvolvedCard.jsx]: I think adding `md:w-1/3` will keep the cards consistent. Between the small and large breakpoint it is ok if they don't remain the same size

Comment (Caposto) [reply src/_components/GetInvolvedCard.jsx]: Can you also change the title text size to `text-3xl` and the description text size to `text-xl`. The `lg` breakpoint text can be left the same. I was playing around and this helped avoid content dropping and being uneven

**Review by Caposto — CHANGES_REQUESTED** [review]

File: src/_components/ProjectCard.jsx [hunk 2]
```diff
@@ -10,7 +10,7 @@ export default function ProjectCard({
 }) {
   const box_styling = status === "Completed" ? "bg-primary" : "bg-maroon";
   return (
-    <figure className="flex-col flex w-full border border-black rounded-lg lg:p-10 p-8 lg:max-w-[600px]">
+    <figure className="flex-col flex w-full border border-black rounded-lg lg:p-10 p-8">
       <div className="flex flex-row justify-start items-center w-full">
         <p
           className={`${box_styling} px-2 py-1 max-w-max my-3 rounded-md text-white lg:text-md text-md font-medium`}
```
Comment (ShawnAviles) [inline src/_components/ProjectCard.jsx]: I think this should be a bit larger, just a bit hard to read

File: src/_components/ProjectCard.jsx [hunk 3]
```diff
@@ -10,7 +10,7 @@ export default function ProjectCard({
 }) {
   const box_styling = status === "Completed" ? "bg-primary" : "bg-maroon";
   return (
-    <figure className="flex-col flex w-full border border-black rounded-lg lg:p-10 p-8 lg:max-w-[600px]">
```
Comment (ShawnAviles) [inline src/_components/ProjectCard.jsx:13]: I think there should be some more consistent horiztonal padding to the left and right of the whole cards section. As of rn, if on a large screen, the whole page is filled with the card. This is how it looks on an ultrawide lol:

Screenshot 2025-01-29 at 7 18 01 PM

I think you could add something like this `md:max-w-[1440px] md:mx-auto` so that the section is centered and limited to the desktop width. this would need to be consistent with the get involved section too

**Review by ShawnAviles — CHANGES_REQUESTED** [review]
Some small changes but overall looks clean

File: src/_components/ProjectCard.jsx (hunk 3 above)
Comment (ShawnAviles) [reply src/_components/ProjectCard.jsx:13]: @Caposto What do you think about limiting the width

Comment (aemerson1) [reply src/_components/ProjectCard.jsx:13]: Here's what the card section looks like with limiting the width and mx:auto on a larger screen:
image

On a smaller laptop screen:
image

**Review by ShawnAviles — APPROVED** [review]
Thanks for making the changes!

**Review by Caposto — APPROVED** [review]
