### PR TITLE
Fix Mission Hero Resizing

### LINKED ISSUE #210: Mission Hero Image Expanding Too Far
In the recent push of #207, the hero image sometimes doesn't properly scale in some instances. See the screen recording below.

https://github.com/user-attachments/assets/a9cf3f04-04ac-4f5b-8dc9-104adf5a22db

### PR DESCRIPTION
**Pull request by cengelbart39**
## Description

Fixes the hero image resizing itself too far by restricting the maximum width it can resize to.

## Related Issues
* #191 
* #207 
* Resolves #210 (Shows incorrect behavior)

## Screen Recording

https://github.com/user-attachments/assets/8fc9aaeb-cef3-44ba-84e8-d619b65bb587

### CODE REVIEW

File: src/_includes/_layouts/Mission.jsx [hunk 1]
```diff
@@ -30,12 +30,12 @@ export default ({ comp, values }) => (
               text={"Read More"}
             />
           </div>
-          <div className="lg:w-5/12 lg:absolute lg:right-20 lg:full flex items-end max-lg:flex-1 max-lg:px-10">
-            <div className="max-lg:p-8">
+          <div className="lg:w-5/12 lg:absolute lg:right-20 lg:top-1/2 lg:-translate-y-1/2 flex items-center justify-center max-lg:mt-8 max-lg:px-10">
```
Comment (ShawnAviles) [inline src/_includes/_layouts/Mission.jsx]: Just wanted to share here that a slightly better (more agnostic) approach for the CSS styling would be to use flexbox rather that position absolute to place the image on the right side of the div. 

_**Note**: Absolute positioning an element is good when you want to overlay a div upon another but we can actually take advantage of having a flex display here since it is side-by-side_ 🥳 

Using flexbox allows you to have less CSS classes and prevent something like "image growing larger than the container div" issues from happening as flex parents can contains it's own children pretty easily. Another reason is that hard coding, pixel values is typically frowned upon [[ref](https://github.com/andredesousa/css-best-practices?tab=readme-ov-file#avoid-hard-coded-values)]. So whenever you have to hardcode pixels it usually means there is a cleaner approach somewhere.

**Comment by ShawnAviles** [comment]
# After changes

Ensuring size of image is proper when resizing:

Screenshot 2024-10-15 at 11 56 34 PM

Video:
https://github.com/user-attachments/assets/cbe8a89c-260e-4dc4-9217-3290dd3fb111


---

I also made some changes to the padding of other elements to ensure the mobile view is correct as well-- so the image and text is centered with appropriate padding on top


Mobile view: 
Screenshot 2024-10-15 at 11 55 52 PM

**Review by ShawnAviles — DISMISSED** [review]
I added some of my own changes too so if I could get another pair of eyes from @Caposto and @cengelbart39 to double check and make sure it looks good then we'll be good to merge

**Comment by ShawnAviles** [comment]
Overall, good work @cengelbart39 🚀

**Comment by cengelbart39** [comment]
It looks good to me.

I'm not that familiar with CSS so thanks for sharing @ShawnAviles

**Review by Caposto — APPROVED** [review]
LGTM
